import type { Metadata } from "next";
import "./globals.css";
import Providers from './providers';

import Navbar from "@/components/shared/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<
  {  
    children: React.ReactNode;
  
  }>) {
  return (
    <html lang="en" className="dark h-full antialiased">
      <body className="min-h-full flex flex-col">
        
        <Providers>
          <Navbar />
          {children}
        </Providers>

      </body>
    </html>
  );
}
